# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/Kise-Research-Centre-Research-Project/project_1/project_1.cache/wt [current_project]
set_property parent.project_path Z:/Kise-Research-Centre-Research-Project/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo z:/Kise-Research-Centre-Research-Project/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet z:/Kise-Research-Centre-Research-Project/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
set_property used_in_implementation false [get_files z:/Kise-Research-Centre-Research-Project/project_1/project_1.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp]
read_verilog -library xil_defaultlib Z:/Kise-Research-Centre-Research-Project/project_1/project_1.srcs/sources_1/new/main.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc Z:/Kise-Research-Centre-Research-Project/project_1/project_1.srcs/constrs_1/new/main.xdc
set_property used_in_implementation false [get_files Z:/Kise-Research-Centre-Research-Project/project_1/project_1.srcs/constrs_1/new/main.xdc]


synth_design -top m_main -part xc7a100tcsg324-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef m_main.dcp

catch { report_utilization -file m_main_utilization_synth.rpt -pb m_main_utilization_synth.pb }
